export default {
    LOGIN: 'LOGIN',                                         //profile constants
    LOGOUT: 'LOGOUT',

    SIGN_UP : 'SIGN_UP',
    SHOW_LOGIN: 'SHOW_LOGIN',
    GET_CLIENTS: 'GET_CLIENTS',
    BLOCK_CLIENT: 'BLOCK_CLIENT',//clients constants
    SHOW_SIGN_UP: 'SHOW_SIGN_UP',
    CHANGE_PROFILE: 'CHANGE_PROFILE',
    SHOW_CLIENT_MODAL: 'SHOW_CLIENT_MODAL',
    HIDE_CLIENT_MODAL: 'HIDE_CLIENT_MODAL',
    SHOW_CHANGE_PASSWORD: 'SHOW_CHANGE_PASSWORD'
};